import { type Page, expect, test } from '@playwright/test'
import { openPanel } from './panels'

const web = (page: Page) => page.getByRole('button', { name: /Web application.*shop\.web/ })
const other = (page: Page) => page.getByRole('treeitem').filter({ hasText: 'customer' }).getByRole('button').first()
const inspector = (page: Page) => page.getByRole('region', { name: 'Инспектор элемента' })
const title = (page: Page) => inspector(page).getByLabel('Название', { exact: true })
const draftDialog = (page: Page) => page.getByRole('dialog', { name: 'Сохранить изменения элемента?' })

async function requestCanvasRemoval(page: Page, route: 'keyboard' | 'quick action'): Promise<void> {
  await openPanel(page, 'Код')
  await expect(inspector(page)).toBeHidden()
  const canvas = page.getByRole('region', { name: 'Холст диаграммы' })
  if (route === 'keyboard') {
    await canvas.focus()
    await canvas.press('Delete')
  } else {
    await page.getByRole('button', { name: 'Закрыть панель «Код LikeC4»' }).click()
    await page.locator('.react-flow__node[data-id="shop.web"]').click({ button: 'right' })
    const remove = page.getByRole('menu', { name: 'Действия выбранной сущности', exact: true })
      .getByRole('menuitem', { name: /Удалить/ })
    await expect(remove).toBeEnabled()
    await remove.click()
  }
}

test.beforeEach(async ({ page }) => {
  // Each Playwright test has its own browser context/storage; never clear a user's database.
  await page.goto('/')
  await openPanel(page, 'Структура')
  await expect(web(page)).toBeVisible()
  await web(page).click()
  await openPanel(page, 'Инспектор')
  await expect(title(page)).toHaveValue('Web application')
})

test('T03-a keeps title, description, tags and caret across unrelated panel renders', async ({ page }) => {
  await page.getByRole('button', { name: 'Код', exact: true }).click()
  const source = page.getByLabel('Исходный код LikeC4')
  await source.fill((await source.inputValue()).replace('element actor', 'tag ui\n  element actor'))
  await openPanel(page, 'Инспектор')
  await inspector(page).getByText('Подробности', { exact: true }).click()
  await expect(inspector(page).getByRole('checkbox', { name: '#ui' })).toBeVisible()
  await title(page).fill('Несохранённое название')
  await inspector(page).getByLabel('Описание', { exact: true }).fill('Несохранённое описание')
  await inspector(page).getByRole('checkbox', { name: '#ui' }).check()
  const tags = await inspector(page).getByRole('checkbox').evaluateAll(inputs =>
    inputs.map(input => {
      return { name: input.parentElement?.textContent, checked: (input as HTMLInputElement).checked }
    })
  )
  await title(page).focus()
  await title(page).press('Home')
  await title(page).press('ArrowRight')
  const caret = await title(page).evaluate(input => (input as HTMLInputElement).selectionStart)
  await page.getByRole('button', { name: 'Структура', exact: true }).click()
  await expect(inspector(page)).toBeHidden()
  await openPanel(page, 'Инспектор')
  await expect(title(page)).toHaveValue('Несохранённое название')
  expect(await title(page).evaluate(input => (input as HTMLInputElement).selectionStart)).toBe(caret)
  await openPanel(page, 'Код')
  await expect(inspector(page)).toBeHidden()
  await openPanel(page, 'Инспектор')
  await expect(inspector(page).getByLabel('Описание', { exact: true })).toHaveValue('Несохранённое описание')
  expect(
    await inspector(page).getByRole('checkbox').evaluateAll(inputs =>
      inputs.map(input => {
        return { name: input.parentElement?.textContent, checked: (input as HTMLInputElement).checked }
      })
    ),
  ).toEqual(tags)
  await page.getByRole('button', { name: 'Инспектор', exact: true }).click()
  await expect(inspector(page)).toBeHidden()
  await page.getByRole('button', { name: 'Инспектор', exact: true }).click()
  await expect(title(page)).toHaveValue('Несохранённое название')
  await expect(inspector(page).getByLabel('Описание', { exact: true })).toHaveValue('Несохранённое описание')
  await expect(inspector(page).getByRole('checkbox', { name: '#ui' })).toBeChecked()
})

test('T03-b stay and Escape preserve the old selection; discard explicitly releases navigation', async ({ page }) => {
  await title(page).fill('Черновик')
  await openPanel(page, 'Структура')
  await other(page).click()
  await expect(draftDialog(page)).toBeVisible()
  await draftDialog(page).getByRole('button', { name: 'Остаться', exact: true }).click()
  await expect(draftDialog(page)).toBeHidden()
  await expect(title(page)).toHaveValue('Черновик')
  await expect(title(page)).toBeFocused()
  await openPanel(page, 'Структура')
  await other(page).click()
  await page.keyboard.press('Escape')
  await expect(draftDialog(page)).toBeHidden()
  await expect(title(page)).toHaveValue('Черновик')
  await expect(title(page)).toBeFocused()
  await openPanel(page, 'Структура')
  await other(page).click()
  await draftDialog(page).getByRole('button', { name: 'Отбросить и перейти' }).click()
  await expect(draftDialog(page)).toBeHidden()
  await openPanel(page, 'Инспектор')
  await expect(title(page)).not.toHaveValue('Черновик')
  await openPanel(page, 'Структура')
  await web(page).click()
  await openPanel(page, 'Инспектор')
  await expect(title(page)).toHaveValue('Web application')
})

test('T03-b save-and-continue confirms the old element before selecting another', async ({ page }) => {
  await title(page).fill('Сохранённый storefront')
  await openPanel(page, 'Структура')
  await other(page).click()
  await draftDialog(page).getByRole('button', { name: 'Сохранить и перейти' }).click()
  await expect(draftDialog(page)).toBeHidden()
  await openPanel(page, 'Инспектор')
  await expect(title(page)).not.toHaveValue('Сохранённый storefront')
  const saved = page.getByRole('button', { name: /Сохранённый storefront.*shop\.web/ })
  await openPanel(page, 'Структура')
  await saved.click()
  await openPanel(page, 'Инспектор')
  await expect(title(page)).toHaveValue('Сохранённый storefront')
  await expect(inspector(page).getByRole('status')).toHaveCount(0)
})

test('T03-b Stay prevents creation before mutation; discard releases one keyboard creation', async ({ page }) => {
  await page.getByRole('button', { name: 'Код', exact: true }).click()
  const source = page.getByLabel('Исходный код LikeC4')
  const before = await source.inputValue()
  await openPanel(page, 'Структура')
  // Count semantic tree entries even when the dirty-draft modal hides their panel.
  // Navigation still opens Structure explicitly; this is not a visibility assertion.
  const tree = page.getByRole('treeitem', { includeHidden: true })
  const beforeCount = await tree.count()
  const canvas = page.getByRole('region', { name: 'Холст диаграммы' })
  await expect(page.locator('.react-flow__pane').first()).toBeVisible()
  await openPanel(page, 'Инспектор')
  await title(page).fill('Черновик перед созданием')

  await canvas.focus()
  await page.keyboard.press('1')
  await page.keyboard.press('Enter')
  await expect(draftDialog(page)).toBeVisible()
  await expect(source).toHaveValue(before)
  await expect(tree).toHaveCount(beforeCount)
  await draftDialog(page).getByRole('button', { name: 'Остаться', exact: true }).click()
  await expect(draftDialog(page)).toBeHidden()
  await expect(title(page)).toHaveValue('Черновик перед созданием')
  await openPanel(page, 'Структура')
  await expect(web(page)).toHaveAttribute('aria-current', 'true')
  await expect(source).toHaveValue(before)
  await expect(tree).toHaveCount(beforeCount)

  await canvas.focus()
  await page.keyboard.press('1')
  await page.keyboard.press('Enter')
  await expect(draftDialog(page)).toBeVisible()
  await draftDialog(page).getByRole('button', { name: 'Отбросить и перейти' }).click()
  await expect(draftDialog(page)).toBeHidden()
  await expect(tree).toHaveCount(beforeCount + 1)
  await expect(source).not.toHaveValue(before)
  await expect(source).not.toHaveValue(/Черновик перед созданием/)
  const inlineTitle = page.getByRole('textbox', { name: 'Название элемента на холсте' })
  await expect(inlineTitle).toBeVisible()
  await inlineTitle.press('Escape')
  await openPanel(page, 'Структура')
  await expect(web(page)).not.toHaveAttribute('aria-current', 'true')
  await openPanel(page, 'Инспектор')
  await expect(title(page)).not.toHaveValue('Черновик перед созданием')
  await page.getByRole('button', { name: 'Отменить последнее изменение' }).click()
  await expect(source).toHaveValue(before)
  await expect(tree).toHaveCount(beforeCount)
})

test('T03-b rejected identifier save retains the draft and pending navigation', async ({ page }) => {
  await inspector(page).getByText('Подробности', { exact: true }).click()
  await inspector(page).getByLabel('Локальный ID').fill('bad id')
  await openPanel(page, 'Структура')
  await other(page).click()
  await draftDialog(page).getByRole('button', { name: 'Сохранить и перейти' }).click()
  await expect(draftDialog(page).getByRole('alert')).toContainText('не подтверждены')
  await expect(draftDialog(page)).toBeVisible()
  await draftDialog(page).getByRole('button', { name: 'Остаться', exact: true }).click()
  await expect(inspector(page).getByLabel('Локальный ID')).toHaveValue('bad id')
  await expect(title(page)).toHaveValue('Web application')
  await openPanel(page, 'Структура')
  await expect(web(page)).toBeVisible()
})

test('T03-b same-ID committed update shows a conflict and requires explicit reload', async ({ page }) => {
  await title(page).fill('Черновик пользователя')
  await page.getByRole('button', { name: 'Код', exact: true }).click()
  const source = page.getByLabel('Исходный код LikeC4')
  const before = await source.inputValue()
  expect(before).toContain('Web application')
  await source.fill(before.replace('Web application', 'Внешнее название'))
  await openPanel(page, 'Структура')
  await expect(page.getByRole('button', { name: /Внешнее название.*shop\.web/ })).toBeVisible()
  await openPanel(page, 'Инспектор')
  await expect(title(page)).toHaveValue('Черновик пользователя')
  await expect(inspector(page).getByRole('region', { name: 'Конфликт изменений' })).toBeVisible()
  await expect(inspector(page).getByRole('button', { name: 'Сохранить свойства' })).toBeDisabled()
  page.once('dialog', dialog => dialog.dismiss())
  await inspector(page).getByRole('button', { name: 'Загрузить актуальные значения' }).click()
  await expect(title(page)).toHaveValue('Черновик пользователя')
  page.once('dialog', dialog => dialog.accept())
  await inspector(page).getByRole('button', { name: 'Загрузить актуальные значения' }).click()
  await expect(title(page)).toHaveValue('Внешнее название')
  await expect(inspector(page).getByRole('region', { name: 'Конфликт изменений' })).toHaveCount(0)
})

test('T03-c confirmed save synchronizes normalized inputs and exact Undo/Redo source', async ({ page }) => {
  await page.getByRole('button', { name: 'Код', exact: true }).click()
  const source = page.getByLabel('Исходный код LikeC4')
  const before = await source.inputValue()
  await openPanel(page, 'Инспектор')
  await title(page).fill('  Подтверждённое название  ')
  await inspector(page).getByRole('button', { name: 'Сохранить свойства' }).click()
  await expect(title(page)).toHaveValue('Подтверждённое название')
  await expect(inspector(page).getByRole('status')).toHaveCount(0)
  const saved = await source.inputValue()
  expect(saved).not.toBe(before)
  await page.getByRole('button', { name: 'Отменить последнее изменение' }).click()
  await expect(title(page)).toHaveValue('Web application')
  await expect(source).toHaveValue(before)
  await page.getByRole('button', { name: 'Повторить отменённое изменение' }).click()
  await expect(title(page)).toHaveValue('Подтверждённое название')
  await expect(source).toHaveValue(saved)
})

for (const route of ['keyboard', 'quick action'] as const) {
  test(`hidden dirty Inspector guards canvas ${route} removal: Stay preserves, discard opens confirmation`, async ({ page }) => {
    await title(page).fill('Черновик перед удалением')
    await expect(inspector(page).getByRole('button', { name: 'Удалить элемент' })).toBeDisabled()
    const source = page.getByLabel('Исходный код LikeC4')
    const before = await source.inputValue()
    const removal = page.getByRole('dialog', { name: 'Удалить элемент?' })

    await requestCanvasRemoval(page, route)
    await expect(draftDialog(page)).toBeVisible()
    await expect(removal).toBeHidden()
    await expect(source).toHaveValue(before)
    await expect(draftDialog(page).getByRole('button', { name: 'Сохранить и перейти' })).toBeEnabled()
    await expect(draftDialog(page).getByRole('button', { name: 'Отбросить и перейти' })).toBeEnabled()
    await draftDialog(page).getByRole('button', { name: 'Остаться', exact: true }).click()
    await expect(draftDialog(page)).toBeHidden()
    await expect(removal).toBeHidden()
    await openPanel(page, 'Инспектор')
    await expect(title(page)).toHaveValue('Черновик перед удалением')
    await expect(source).toHaveValue(before)
    await expect(page.locator('.react-flow__node[data-id="shop.web"]')).toBeVisible()

    await requestCanvasRemoval(page, route)
    await expect(draftDialog(page)).toBeVisible()
    await expect(removal).toBeHidden()
    await draftDialog(page).getByRole('button', { name: 'Отбросить и перейти' }).click()
    await expect(draftDialog(page)).toBeHidden()
    await expect(removal).toBeVisible()
    await expect(removal).toHaveAttribute('data-removal-target', 'shop.web')
    await expect(source).toHaveValue(before)
    await removal.getByRole('button', { name: 'Отмена', exact: true }).click()
    await expect(removal).toBeHidden()
    await openPanel(page, 'Инспектор')
    await expect(title(page)).toHaveValue('Web application')
    await expect(source).toHaveValue(before)
  })

  test(`hidden dirty Inspector saves renamed identity before canvas ${route} removal`, async ({ page }) => {
    await inspector(page).getByText('Подробности', { exact: true }).click()
    await inspector(page).getByLabel('Локальный ID').fill('client_guard')
    const source = page.getByLabel('Исходный код LikeC4')
    const before = await source.inputValue()
    const removal = page.getByRole('dialog', { name: 'Удалить элемент?' })

    await requestCanvasRemoval(page, route)
    await expect(draftDialog(page)).toBeVisible()
    await expect(removal).toBeHidden()
    await expect(source).toHaveValue(before)
    await draftDialog(page).getByRole('button', { name: 'Сохранить и перейти' }).click()
    await expect(draftDialog(page)).toBeHidden()
    await expect(removal).toBeVisible()
    // The pending callback must read the current selection after the rename commit.
    await expect(removal).toHaveAttribute('data-removal-target', 'shop.client_guard')
    await expect(source).toHaveValue(/client_guard = component/)
    await expect(source).toHaveValue(/shop\.client_guard -> customer/)
    await expect(source).not.toHaveValue(/shop\.web/)
    const renamed = await source.inputValue()
    await removal.getByRole('button', { name: 'Удалить', exact: true }).click()
    await expect(removal).toBeHidden()
    await expect(source).not.toHaveValue(/\bclient_guard\b/)
    await expect(page.locator('.react-flow__node[data-id="shop.client_guard"]')).toHaveCount(0)
    const removed = await source.inputValue()
    const undo = page.getByRole('button', { name: 'Отменить последнее изменение' })
    await undo.click()
    await expect(source).toHaveValue(renamed)
    await undo.click()
    await expect(source).toHaveValue(before)
    const redo = page.getByRole('button', { name: 'Повторить отменённое изменение' })
    await redo.click()
    await expect(source).toHaveValue(renamed)
    await redo.click()
    await expect(source).toHaveValue(removed)
  })
}
